// <auto-generated />
using System;
using MatchupCompanion.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchupCompanion.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PrimaryRoleId")
                        .HasColumnType("int");

                    b.Property<string>("RiotChampionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PrimaryRoleId");

                    b.HasIndex("RiotChampionId")
                        .IsUnique();

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 22, 22, 58, 698, DateTimeKind.Utc).AddTicks(9594),
                            Name = "Aatrox",
                            PrimaryRoleId = 1,
                            RiotChampionId = "266",
                            Title = "the Darkin Blade",
                            UpdatedAt = new DateTime(2026, 1, 15, 22, 22, 58, 698, DateTimeKind.Utc).AddTicks(9597)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 22, 22, 58, 698, DateTimeKind.Utc).AddTicks(9601),
                            Name = "Ahri",
                            PrimaryRoleId = 3,
                            RiotChampionId = "103",
                            Title = "the Nine-Tailed Fox",
                            UpdatedAt = new DateTime(2026, 1, 15, 22, 22, 58, 698, DateTimeKind.Utc).AddTicks(9602)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 22, 22, 58, 698, DateTimeKind.Utc).AddTicks(9604),
                            Name = "Zed",
                            PrimaryRoleId = 3,
                            RiotChampionId = "238",
                            Title = "the Master of Shadows",
                            UpdatedAt = new DateTime(2026, 1, 15, 22, 22, 58, 698, DateTimeKind.Utc).AddTicks(9605)
                        });
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.Matchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EnemyChampionId")
                        .HasColumnType("int");

                    b.Property<string>("GeneralAdvice")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PlayerChampionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EnemyChampionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("PlayerChampionId", "EnemyChampionId", "RoleId")
                        .IsUnique();

                    b.ToTable("Matchups");
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.MatchupTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchupId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("MatchupId");

                    b.HasIndex("Priority");

                    b.ToTable("MatchupTips");
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Línea superior",
                            Name = "Top"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Jungla",
                            Name = "Jungle"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Línea media",
                            Name = "Mid"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tirador (Bot Lane)",
                            Name = "ADC"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Soporte (Bot Lane)",
                            Name = "Support"
                        });
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.Champion", b =>
                {
                    b.HasOne("MatchupCompanion.API.Models.Entities.Role", "PrimaryRole")
                        .WithMany("Champions")
                        .HasForeignKey("PrimaryRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryRole");
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.Matchup", b =>
                {
                    b.HasOne("MatchupCompanion.API.Models.Entities.Champion", "EnemyChampion")
                        .WithMany("MatchupsAsEnemyChampion")
                        .HasForeignKey("EnemyChampionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatchupCompanion.API.Models.Entities.Champion", "PlayerChampion")
                        .WithMany("MatchupsAsPlayerChampion")
                        .HasForeignKey("PlayerChampionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatchupCompanion.API.Models.Entities.Role", "Role")
                        .WithMany("MatchupsAsPlayerRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnemyChampion");

                    b.Navigation("PlayerChampion");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.MatchupTip", b =>
                {
                    b.HasOne("MatchupCompanion.API.Models.Entities.Matchup", "Matchup")
                        .WithMany("Tips")
                        .HasForeignKey("MatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matchup");
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.Champion", b =>
                {
                    b.Navigation("MatchupsAsEnemyChampion");

                    b.Navigation("MatchupsAsPlayerChampion");
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.Matchup", b =>
                {
                    b.Navigation("Tips");
                });

            modelBuilder.Entity("MatchupCompanion.API.Models.Entities.Role", b =>
                {
                    b.Navigation("Champions");

                    b.Navigation("MatchupsAsPlayerRole");
                });
#pragma warning restore 612, 618
        }
    }
}
